# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('df_name', models.CharField(max_length=20)),
                ('df_pwd', models.CharField(max_length=30)),
                ('df_email', models.CharField(max_length=30)),
                ('df_phone', models.CharField(max_length=20)),
                ('df_addr', models.CharField(max_length=50)),
                ('df_sname', models.CharField(max_length=20)),
                ('df_emailCode', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
